routes/web.php
<?php

Route::permanentRedirect('home', '/');
Route::view('support/thank-you', 'member.thanks')->name('support.thanks');
Route::view('/adminss', 'admin')->name('adminpage');
Route::view('mailable', 'admin.bantuan.template_mail');

Route::prefix('admin')->namespace('Auth')->name('admin.')->group(function () {
  Route::get('login','LoginController@showLoginForm')->name('login');
  Route::post('login', 'LoginController@login')->name('login');
  Route::get('register','RegisterController@showRegistrationForm')->name('register');
  Route::post('register', 'RegisterController@register')->name('register');
  Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::prefix('member')->namespace('Auth')->name('member.')->group(function () {
  Route::get('login','MemberLoginController@showLoginForm')->name('login');
  Route::post('login', 'MemberLoginController@login')->name('login');
  Route::get('register','MemberLoginController@showRegisterPage')->name('register');
  Route::post('register', 'MemberLoginController@register')->name('register');
  Route::post('logout', 'MemberLoginController@logout')->name('logout');
});

Route::namespace('Home')->name('home.')->group(function () {
  Route::get('/', 'HomeController@landing');
  Route::get('about', 'HomeController@about')->name('about');
  Route::get('mitra', 'HomeController@mitra')->name('mitra');
  Route::post('mitra', 'HomeController@storeMitra')->name('mitra.store');
  Route::get('support', 'HomeController@support')->name('support');
  Route::post('support', 'HomeController@supportStore')->name('support.store');
  Route::get('promo', 'HomeController@promosi')->name('promosi');
  Route::get('promo/{slug}', 'HomeController@showPromo')->name('promo.show');
  Route::get('syarat-dan-ketentuan', 'HomeController@peraturan')->name('peraturan');
  Route::get('profil', 'HomeController@profil')->name('profil');
  Route::get('profil/asd', 'HomeController@profil')->name('profil');
  Route::post('klien/create', 'HomeController@klienStore')->name('klien.store');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('auth')->group(function () {
  Route::resource('dashboard', 'DashboardController');
  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::put('member/activating/{id}', 'MemberController@activating')->name('member.activating');
  Route::resource('member', 'MemberController');
  Route::get('klien/edit-api/{id?}', 'KlienController@editApi')->name('klien.editAjax');
  Route::post('klien/update-api/{id?}', 'KlienController@updateApi')->name('klien.updateAjax');
  Route::resource('klien', 'KlienController');
  Route::get('penghasilan/fee', 'PenghasilanController@fee')->name('penghasilan.fee');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('landing-page', 'LandingPageController');
  Route::resource('promosi', 'PromosiController');
  Route::get('promosi/{slug}', 'PromosiController@show')->name('promosi.show');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
  Route::resource('partner', 'PartnerController');
  Route::resource('fitur', 'FiturController');
  Route::resource('mitra', 'MitraController');
});

Route::prefix('member')->namespace('Member')->name('member.')->middleware(['auth:member'])->group(function () {
  Route::resource('dashboard', 'DashboardController');

  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::resource('klien', 'KlienController');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('promosi', 'PromosiController');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
});

Route::namespace('Home')->name('home.')->group(function () {
Route::get('/{promo}/{member}', 'HomeController@getPromo')->name('getpromo')
->where([
  'promo' => '^(?!admin$).*$',
  'promo' => '^(?!member$).*$',
  'promo' => '^(?!profil$).*$',
  'promo' => '^(?!klien$).*$',
  'promo' => '^(?!support$).*$'
  ]);
});

resources/views/about.blade.php
@extends('layouts.master_static')
@section('title', 'Tentang Kami')
@section('header')
  <header id="aboutPage">
    <div class="overlay">
      @include('temp.nav')
      <div class="header__caption">
        <h1>Tentang Kami</h1>
      </div>
    </div>
  </header>
@endsection
@section('content')
  <main>
    <section>
      <div class="container">
        <h1>PT Jaya Bina Konsultan Group</h1>
        <p>Adalah PT yang bekerja untuk Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan ante a dapibus auctor.
          Morbi sit amet sollicitudin arcu.</p>
      </div>
    </section>
    <section>
      <div class="container">
        <h1>Team Kami</h1>
        <div class="row justify-content-center">
          <figure class="col-12 col-md-4">
            <img src="assets/img/team/achmad.jpeg" height="200" alt="our team">
            <figcaption>
              <p>Achmad Ridwan</p>
              <p><small>komisaris</small></p>
            </figcaption>
          </figure>
          <figure class="col-12 col-md-4">
            <img src="assets/img/team/adhitya.jpg" height="200" alt="our team">
            <figcaption>
              <p>Helmi Faizal</p>
              <p><small>Direktur Operasional</small></p>
            </figcaption>
          </figure>
          <figure class="col-12 col-md-4">
            <img src="assets/img/team/eti.jpg" height="200" alt="our team">
            <figcaption>
              <p>M. Adhitya Arjanggi</p>
              <p><small>Direktur</small></p>
            </figcaption>
          </figure>
          <figure class="col-12 col-md-4">
            <img src="assets/img/team/helmi.jpeg" height="200" alt="our team">
            <figcaption>
              <p>Eti</p>
              <p><small>Tim Support</small></p>
            </figcaption>
          </figure>
          <figure class="col-12 col-md-4">
            <img src="assets/img/team/nurtiyas.jpg" height="200" alt="our team">
            <figcaption>
              <p>Nurtiyas</p>
              <p><small>Direktur Utama</small></p>
            </figcaption>
          </figure>
        </div>
      </div>
    </section>
  </main>
@endsection

resources/views/faq.blade.php
@extends('layouts.master_static')
@section('title', 'Bantuan Untukmu')
@section('header')
  <header id="supportPage">
    @include('temp.nav')
    <div class="overlay">
      <div class="header__caption">
        <h1 class="mb-3 mb-md-4">Tanyakan Apa Yang Ingin Kamu Tanya</h1>
      </div>
      @if (Session::has('success_message'))
      <div class="col-6 alert-success message-session">
      		Bantuanmu telah terkirim dan akan dibalas dalam 2x24 jam
      </div>
      @endif
    </div>
  </header>
@endsection
@section('content')
  <section>
    <div class="container">
      <h1>kirim pertanyaanmu melalui form ini</h1>
      <form action="{{ route('home.support.store') }}" class="row flex-column mx-0" method="post">
        @csrf
        <div class="col-12 px-0 mb-4">
          @auth ('member')
            <input type="email" name="email" placeholder="Email Kamu" value="{{ Auth::guard('member')->user()->email }}" readonly>
          @else
            <input type="email" name="email_pengirim" placeholder="Email Kamu">
          @endauth
        </div>
        <div class="col-12 px-0 mb-3">
          <textarea name="pertanyaan" rows="12" placeholder="Apa yang ingin kamu tanyakan?"></textarea>
        </div>
        <button type="submit" name="button" class="btn-secondary col-md-auto align-self-end">
          kirim pertanyaanmu
          <box-icon name='send' type='solid' color="white"></box-icon>
        </button>
      </form>
    </div>
  </section>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mitra.blade.php
@extends('layouts.master_static')
@section('title', 'Mari Bermitra Dengan Kami')
@section('css')
  <style media="screen">
    .alert {
      position: fixed;
      top: 90px;
      padding: .75rem 1.25rem;
      border: 1px solid transparent;
      border-radius: .25rem;
      z-index: 3;
      width: 80%;
      max-width: 700px;
    }
    .alert-success {
      background-color: #d4edda;
      color: #155724;
      border-color: #c3e6cb;
    }
  </style>
@endsection
@section('header')
  <header id="mitraPage">
    <div class="overlay">
      @if (Session::has('success_message') || Session::has('failed_message'))
    	<div class="col-12 message-session">
    		<div class="alert alert-success {{(Session::has('success_message'))? 'success' : 'danger'}} text-center">
    			{{(Session::has('success_message'))? Session::get('success_message') : Session::get('failed_message')}}
    		</div>
    	</div>
    	@endif
      @include('temp.nav')
      <div class="header__caption">
        <h1>Ayo Bermitra Bersama Kami!</h1>
      </div>
      <a href="#caraBermitra" class="btn-secondary col-7 col-md-auto">Begini caranya <box-icon name='chevrons-down' color="white"></box-icon></a>
    </div>
  </header>
@endsection
@section('content')
  <section id="keuntunganSection">
    <div class="container">
      <h1>Apa Yang Akan Kamu Dapatkan?</h1>
      <div class="row">
        <figure class="col-12 col-md-4">
          <img src="{{ asset('assets/img/relasi.svg') }}" height="75" alt="Mitra Image">
          <figcaption>
            Relasi Dengan <br> Berbagai Jenis Bisnis
          </figcaption>
        </figure>
        <figure class="col-12 col-md-4">
          <img src="{{ asset('assets/img/support.svg') }}" height="75" alt="Mitra Image">
          <figcaption>Bantuan <br> Secara Real Time</figcaption>
        </figure>
        <figure class="col-12 col-md-4">
          <img src="{{ asset('assets/img/promosi.svg') }}" height="75" alt="Mitra Image">
          <figcaption>
            Promosi <br> Yang Menjanjikan
          </figcaption>
        </figure>
      </div>
    </div>
  </section>
  <section id="caraBermitra">
    <div class="container">
      <h1>Bagaimana Cara Menjadi Mitra?</h1>
      <div class="row mx-0 flex-column flex-md-row">
        <ol>
          <li>1) Klik tombol <strong>gabung sekarang</strong></li>
          <li>2) Isi form dengan penuh sukacita</li>
          <li>3) Kamu akan mendapatkan email dari kami dalam waktu 1 x 24 jam</li>
        </ol>
        <a href="javascript:void(0);" class="btn-secondary btn-modal">gabung sekarang</a>
        <div class="modal-overlay">
          <div class="modal">
            <div class="modal__header">
              <h1>Daftarkan Bisnismu Sekarang!</h1>
              <small>dan dapatkan keuntungannya</small>
              <span class="modal__close"><box-icon name='x' color="white"></box-icon></span>
            </div>
            <div class="modal__content">
              <form action="{{ route('home.mitra.store') }}" method="post">
                @csrf
                <div class="row flex-column mx-0">
                  <div class="col px-0 mb-4">
                    <input type="text" name="nama" placeholder="Nama Bisnis">
                  </div>
                  <div class="col px-0 mb-4">
                    <input type="email" name="email" placeholder="Email Bisnis">
                  </div>
                  <div class="col px-0 mb-4">
                    <input type="number" name="hp" placeholder="Nomor Handphone">
                  </div>
                  <div class="col px-0 mb-4">
                    <textarea rows="10" name="alamat" placeholder="Alamat Rumah"></textarea>
                  </div>
                  <button type="submit" name="button" class="btn-secondary col-md-auto align-self-end">
                    daftar sekarang
                    <box-icon name='send' type='solid' color="white"></box-icon>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/peraturan.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/native.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/slick-theme.css') }}">
  </head>
  <body id="peraturanPage">
    <nav>
      <span id="brandNav"><a href="{{ url('/') }}">e-bina</a> <box-icon name='menu-alt-right' color="white"></box-icon></span>
      <a href="{{ url('/') }}#jasaSection">jasa</a>
      <a href="{{ url('/') }}#klienSection">klien</a>
      <a href="{{ url('/') }}#hargaSection">harga</a>
      <a href="{{ url('promo') }}">promo</a>
      <a href="{{ url('mitra') }}">mitra</a>
      <a href="{{ url('support') }}">support</a>
      <a href="{{ url('about') }}">tentang kami</a>
      <a href="{{ route('member.login') }}" id="loginBtn">login</a>
    </nav>
    <main>
      <section>
        <div class="container">
          <h1>Kebijakan E-Bina</h1>
          <h2>Selamat datang di E-Bina</h2>
          <p>Syarat & ketentuan yang ditetapkan di bawah ini mengatur pemakaian jasa yang ditawarkan oleh PT. Jaya Bina Konsultan Group terkait penggunaan
            situs www.ebina.id. Pengguna disarankan membaca dengan seksama karena dapat berdampak kepada hak dan kewajiban Pengguna di bawah hukum.</p>
          <p>Berikut adalah beberapa peraturan dan kebijakan dari kami. Peraturan yang tersedia tidak dapat diganggu gugat.</p>
          <div class="row mx-0">
            <div class="col-md-3 px-0">
              <div class="nav flex-column nav-pills" id="v-pills-tab" aria-orientation="vertical" role="tablist" id="v-pills-tab">
                @foreach ($peraturan as $each)
                  <a class="nav-link" id="v-pills-peraturan{{ $each->id }}-tab" data-toggle="pill" href="#v-pills-peraturan{{ $each->id }}" role="tab"
      						aria-controls="v-pills-peraturan{{ $each->id }}" aria-selected="false">{{ $each->judul }}</a>
                @endforeach
              </div>
            </div>
            <div class="col px-0" id="listPeraturan">
              <div class="tab-content" id="v-pills-tabContent">
                @foreach ($peraturan as $each)
      		      <div class="tab-pane fade" id="v-pills-peraturan{{ $each->id }}" role="tabpanel" aria-labelledby="v-pills-peraturan{{ $each->id }}-tab">
      						<h2 class="text-capitalize">{{ $each->judul }}</h2>
      		      	{!! $each->deskripsi !!}
      		      </div>
      					@endforeach
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
    @include('temp.footer')
    <script src="{{ asset('assets/jquery.js') }}" charset="utf-8"></script>
    <script src="{{ asset('assets/native.js') }}" charset="utf-8"></script>
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.js') }}" charset="utf-8"></script>
    <script src="https://unpkg.com/boxicons@latest/dist/boxicons.js"></script>
    <script>
      
    </script>
  </body>
</html>

resources/views/profil.blade.php
@extends('layouts.master_static')
@section('title', 'Profil Kamu')
@section('header')
  <header id="profilPage">
    @include('temp.nav')
    <div class="container">
      <figure>
        <img src="{{ asset('assets/img/team/helmi_profil.svg') }}" height="150" class="d-block mx-auto" alt="Profile Page">
        <figcaption>
          <h1>Helmi Faizal</h1>
          <small><a href=""><box-icon name='mail-send' color="#dd4343"></box-icon><span class="ml-2">helmi@faizal.me</span></a></small>
          <small><a href=""><box-icon name='edit-alt' type='solid' color="orange"></box-icon> Ubah Profilmu</a></small>
        </figcaption>
      </figure>
    </div>
  </header>
@endsection
@section('content')
  <section>
    <div class="container">
      <ul>
        <li class="px-0 col-md-6">
          <span class="d-block">Alamat</span>
          <address>Jalan Swadaya Gudang Baru No.11, RT.6/RW.4, Ciganjur, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta</address>
        </li>
        <li>
          <span class="d-block">Nomor Telephone</span>
          <a href="tel:087xxxxxxxxx">087xxxxxxxxx</a>
        </li>
      </ul>
    </div>
  </section>
@endsection

resources/views/promosi.blade.php
@extends('layouts.master_static')
@section('title', 'Dapatkan Promo Menarik Dari Kami')
@section('css')
  <style media="screen">
    figure figcaption a {
      color: #2d87df;
    }
    figure {
      border: 1px solid #a2a2a2;
    }
    .pagination {
      display: flex;
      justify-content: space-between;
      background-color: inherit;
      border: 1px solid #e2e2e2;
      border-radius: 5px;
    }
    .pagination li {
      transition: all 250ms;
      height: 35px;
      line-height: 35px;
      padding: 0 1rem;
    }
    .pagination li:not(:last-child) {
      border-right: 1px solid #e2e2e2;
    }
    .pagination .active {
      background-color: #3790c6;
      color: #fff;
    }
    .pagination li:not(.active):not(.disabled):hover {
      background-color: #ededed;
    }
    .pagination .disabled {
      color: #cccccc;
    }
    .pagination li:not(.active):not(.disabled) {
      color: #3790c6;
    }
  </style>
@endsection
@section('header')
  <header id="promosiPage">
    @include('temp.nav')
    <div class="overlay">
      <div class="header__caption">
        <h1>Cari Promo Yang <br> Pas Untukmu</h1>
      </div>
    </div>
  </header>
@endsection
@section('content')
  <section>
    <div class="container">
      <div class="row">
        @foreach ($promos as $promo)
          <div class="col-12 col-md-4">
              <figure>
                  <img src="{{ asset('assets/img/' . $promo->gambar) }}" height="200" alt="Promo {{ $promo->title }}">
                  <figcaption>
                    <h2 class="col-12 px-0">{{ $promo->title }}</h2>
                    <a href="{{ route('home.promo.show', $promo->slug) }}" class="col-12 px-0 mb-3" target="">Read More</a>
                    <time>{{ $promo->startDate->format('d F Y') . " - " . $promo->endDate->format('d F Y') }}</time>
                  </figcaption>
              </figure>
          </div>
        @endforeach
      </div>
      <div class="row py-5 align-items-center justify-content-center">
        {{ $promos->links('vendor.pagination.mypaginate') }}
      </div>
    </div>
  </section>
@endsection

resources/views/show_promosi.blade.php
@extends('layouts.master_static')
@section('title', 'Dapatkan Promo Menarik Dari Kami')
@section('css')
  <style media="screen">
    nav {
      background-color: #4096c7;
    }
    figure img {
      width: 100%;
      display: block;
      margin: 0 auto;
    }
    figcaption h1 {
      text-align: center;
      font-size: 33px;
    }
    figcaption > p {
      margin-bottom: 20px;
    }
    figcaption > time {
      text-align: center;
      display: block;
      width: 80%;
      max-width: 350px;
      margin: 0 auto;
      border-radius: 20px;
      padding: 15px 0;
      color: #fff;
      background-color: #2fa7c2;
    }
  </style>
@endsection
@section('header')
    @include('temp.nav')
@endsection
@section('content')
  <section>
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-6 mx-auto">
            <figure class="mt-5">
                <img src="{{ asset('assets/img/' . $promo->gambar) }}" height="200" alt="Promo {{ $promo->title }}">
                <figcaption class="py-3">
                  <h1 class="col-12 px-0 mb-3">{{ $promo->title }}</h1>
                  <p class="card-text">{!! $promo->isi !!}</p>
                  <time>{{ $promo->startDate->format('d F Y') . " - " . $promo->endDate->format('d F Y') }}</time>
                </figcaption>
            </figure>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/support.blade.php
@extends('layouts.master_static')
@section('title', 'Bantuan Untukmu')
@section('header')
  <header id="supportPage">
    @include('temp.nav')
    <div class="overlay">
      <div class="header__caption">
        <h1 class="mb-3 mb-md-4">Kamu Membutuhkan Bantuan?</h1>
        <h4 class="mr-5">Hubungi WhatsApp kami:&nbsp;<a href="https://wa.me/6281280029849">081280029849</a></h4>
        <h4>atau isi form dibawah ini</h4>
      </div>
      @if (Session::has('success_message'))
      <div class="col-6 alert-success message-session">
      		Bantuanmu telah terkirim dan akan dibalas dalam 2x24 jam
      </div>
      @endif
    </div>
  </header>
@endsection
@section('content')
  <section>
    <div class="container">
      <h1>kirim pertanyaanmu melalui form ini</h1>
      <form action="{{ route('home.support.store') }}" class="row flex-column mx-0" method="post">
        @csrf
        <div class="col-12 px-0 mb-4">
          @auth ('member')
            <input type="email" name="email_pengirim" placeholder="Email Kamu" value="{{ Auth::guard('member')->user()->email }}" readonly>
          @else
            <input type="email" name="email_pengirim" placeholder="Email Kamu">
          @endauth
        </div>
        <div class="col-12 px-0 mb-3">
          <input type="text" name="subjek" placeholder="Subjek Pertanyaan Kamu">
        </div>
        <div class="col-12 px-0 mb-3">
          <textarea name="pertanyaan_pengirim" rows="12" placeholder="Apa yang ingin kamu tanyakan?"></textarea>
        </div>
        <button type="submit" name="button" class="btn-secondary col-md-auto align-self-end">
          kirim pertanyaanmu
          <box-icon name='send' type='solid' color="white"></box-icon>
        </button>
      </form>
    </div>
  </section>
@endsection