routes/web.php
<?php

Route::permanentRedirect('home', '/');
Route::view('support/thank-you', 'member.thanks')->name('support.thanks');
Route::view('/adminss', 'admin')->name('adminpage');
Route::view('mailable', 'admin.bantuan.template_mail');

Route::prefix('admin')->namespace('Auth')->name('admin.')->group(function () {
  Route::get('login','LoginController@showLoginForm')->name('login');
  Route::post('login', 'LoginController@login')->name('login');
  Route::get('register','RegisterController@showRegistrationForm')->name('register');
  Route::post('register', 'RegisterController@register')->name('register');
  Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::prefix('member')->namespace('Auth')->name('member.')->group(function () {
  Route::get('login','MemberLoginController@showLoginForm')->name('login');
  Route::post('login', 'MemberLoginController@login')->name('login');
  Route::get('register','MemberLoginController@showRegisterPage')->name('register');
  Route::post('register', 'MemberLoginController@register')->name('register');
  Route::post('logout', 'MemberLoginController@logout')->name('logout');
});

Route::namespace('Home')->name('home.')->group(function () {
  Route::get('/', 'HomeController@landing');
  Route::get('about', 'HomeController@about')->name('about');
  Route::get('mitra', 'HomeController@mitra')->name('mitra');
  Route::post('mitra', 'HomeController@storeMitra')->name('mitra.store');
  Route::get('support', 'HomeController@support')->name('support');
  Route::post('support', 'HomeController@supportStore')->name('support.store');
  Route::get('promo', 'HomeController@promosi')->name('promosi');
  Route::get('promo/{slug}', 'HomeController@showPromo')->name('promo.show');
  Route::get('syarat-dan-ketentuan', 'HomeController@peraturan')->name('peraturan');
  Route::get('profil', 'HomeController@profil')->name('profil');
  Route::get('profil/asd', 'HomeController@profil')->name('profil');
  Route::post('klien/create', 'HomeController@klienStore')->name('klien.store');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('auth')->group(function () {
  Route::resource('dashboard', 'DashboardController');
  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::put('member/activating/{id}', 'MemberController@activating')->name('member.activating');
  Route::resource('member', 'MemberController');
  Route::get('klien/edit-api/{id?}', 'KlienController@editApi')->name('klien.editAjax');
  Route::post('klien/update-api/{id?}', 'KlienController@updateApi')->name('klien.updateAjax');
  Route::resource('klien', 'KlienController');
  Route::get('penghasilan/fee', 'PenghasilanController@fee')->name('penghasilan.fee');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('landing-page', 'LandingPageController');
  Route::resource('promosi', 'PromosiController');
  Route::get('promosi/{slug}', 'PromosiController@show')->name('promosi.show');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
  Route::resource('partner', 'PartnerController');
  Route::resource('fitur', 'FiturController');
  Route::resource('mitra', 'MitraController');
});

Route::prefix('member')->namespace('Member')->name('member.')->middleware(['auth:member'])->group(function () {
  Route::resource('dashboard', 'DashboardController');

  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::resource('klien', 'KlienController');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('promosi', 'PromosiController');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
});

Route::namespace('Home')->name('home.')->group(function () {
Route::get('/{promo}/{member}', 'HomeController@getPromo')->name('getpromo')
->where([
  'promo' => '^(?!admin$).*$',
  'promo' => '^(?!member$).*$',
  'promo' => '^(?!profil$).*$',
  'promo' => '^(?!klien$).*$',
  'promo' => '^(?!support$).*$'
  ]);
});

resources/views/admin/admin_dashboard.blade.php
@extends('temp.main')

@section('title-page', 'E-Bina | Admin - Dashboard')

@section('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section ('title-body', 'Dashboard')

@section('content')
@if (Session::has('success_message') || Session::has('failed_message'))
<div class="col-12 message-session">
	<div class="alert alert-{{(Session::has('success_message'))? 'success' : 'danger'}} text-center">
		{{ (Session::has('success_message'))? Session::get('success_message') : Session::get('failed_message') }}
	</div>
</div>
@endif
<div class="col-12 col-md-6">
	<div class="info-box">
		<span class="info-box-icon bg-info"><i class="fa fa-users"></i></span>
		<div class="info-box-content">
			<span class="info-box-text">Active Member(s)</span>
			<span class="info-box-number">{{ $memberActive }}</span>
		</div>
	</div>
</div>
<div class="col-12 col-md-6">
	<div class="info-box">
		<span class="info-box-icon bg-danger"><i class="fa fa-users"></i></span>
		<div class="info-box-content">
			<span class="info-box-text">Unactive Member(s)</span>
			<span class="info-box-number">{{ $memberUnactive }}</span>
		</div>
	</div>
</div>
<div class="col-md-3 col-12">
	<!-- small card -->
	<div class="small-box bg-primary">
		<div class="inner">
			<h3>{{$all_klien}}</h3>

			<p>Klien : All</p>
		</div>
		<div class="icon">
			<i class="fa fa-users"></i>
		</div>
		<a href="{{route('admin.klien.index')}}" class="small-box-footer">
			More info <i class="fa fa-arrow-circle-right"></i>
		</a>
	</div>
</div>
<div class="col-md-3 col-12">
	<!-- small card -->
	<div class="small-box bg-success">
		<div class="inner">
			<h3>{{$deal_klien}}</h3>

			<p>Klien : Deal</p>
		</div>
		<div class="icon">
			<i class="fa fa-users"></i>
		</div>
		<a href="{{route('admin.klien.index')}}" class="small-box-footer">
			More info <i class="fa fa-arrow-circle-right"></i>
		</a>
	</div>
</div>
<div class="col-md-3 col-12">
	<!-- small card -->
	<div class="small-box bg-warning">
		<div class="inner">
			<h3>{{$negosiasi_klien}}</h3>

			<p>Klien : Negosiasi</p>
		</div>
		<div class="icon">
			<i class="fa fa-users"></i>
		</div>
		<a href="{{route('admin.klien.index')}}" class="small-box-footer">
			More info <i class="fa fa-arrow-circle-right"></i>
		</a>
	</div>
</div>
<div class="col-md-3 col-12">
	<!-- small card -->
	<div class="small-box bg-secondary">
		<div class="inner">
			<h3>{{$pending_klien}}</h3>

			<p>Klien : Pending</p>
		</div>
		<div class="icon">
			<i class="fa fa-users"></i>
		</div>
		<a href="{{route('admin.klien.index')}}" class="small-box-footer">
			More info <i class="fa fa-arrow-circle-right"></i>
		</a>
	</div>
</div>
<div class="col-md-4 col-sm-6 col-12">
	<div class="info-box bg-primary-gradient">
		<span class="info-box-icon"><i class="fa fa-money-bill-wave-alt"></i></span>

		<div class="info-box-content">
			<span class="info-box-text">Total Pendapatan</span>
			<span class="info-box-number">Rp {{number_format($pendapatan+$potensi_pendapatan, 0, ',', '.')}}</span>

			<div class="progress">
				<div class="progress-bar" style="width: 100%"></div>
			</div>
			<span class="progress-description">
				100% from (pendapatan + potensi)
			</span>
		</div>
		<!-- /.info-box-content -->
	</div>
	<!-- /.info-box -->
</div>
<div class="col-md-4 col-sm-6 col-12">
	<div class="info-box bg-success-gradient">
		<span class="info-box-icon"><i class="fa fa-money-bill-wave-alt"></i></span>

		<div class="info-box-content">
			<span class="info-box-text">Pendapatan</span>
			<span class="info-box-number">Rp {{number_format($pendapatan, 0, ',', '.')}}</span>

			<div class="progress">
				<div class="progress-bar" style="width: {{$percentage['pendapatan']}}%"></div>
			</div>
			<span class="progress-description">
				{{(is_float($percentage['pendapatan']))? number_format((float)$percentage['pendapatan'], 1) : $percentage['pendapatan']}}% from total
			</span>
		</div>
		<!-- /.info-box-content -->
	</div>
	<!-- /.info-box -->
</div>
<div class="col-md-4 col-sm-6 col-12">
	<div class="info-box bg-warning-gradient">
		<span class="info-box-icon"><i class="fa fa-money-bill-wave-alt"></i></span>

		<div class="info-box-content">
			<span class="info-box-text">Potensi Pendapatan</span>
			<span class="info-box-number">Rp {{number_format($potensi_pendapatan, 0, ',', '.')}}</span>

			<div class="progress">
				<div class="progress-bar" style="width: {{$percentage['potensi_pendapatan']}}%"></div>
			</div>
			<span class="progress-description">
				{{(is_float($percentage['potensi_pendapatan']))? number_format((float)$percentage['potensi_pendapatan'], 1) : $percentage['potensi_pendapatan']}}% from total
			</span>
		</div>
		<!-- /.info-box-content -->
	</div>
	<!-- /.info-box -->
</div>
<div class="col-lg-8">

	<div class="card">
		<div class="card-header no-border">
			<div class="d-flex justify-content-between">
				<h3 class="card-title">Penghasilan</h3>
				<a href="{{route('admin.penghasilan.index')}}">View All</a>
			</div>
		</div>
		<div class="card-body" style="overflow-x: auto;">
			<div class="col-12" style="min-width: 500px;">
				<div class="d-flex">
					<p class="d-flex flex-column">
						<span>Revenue Over Time</span>
					</p>
					<p class="ml-auto d-flex flex-column text-right">
						<span class="text-muted">Date: {{$startDate}} - {{$endDate}}</span>
					</p>
				</div>
				<!-- /.d-flex -->

				<div class="position-relative mb-4">
					<canvas id="penghasilan-chart" height="200"></canvas>
				</div>

				<div class="d-flex flex-row justify-content-end">
					<span class="mr-2">
						<i class="fa fa-square text-gray"></i> Pending
					</span>

					<span>
						<i class="fa fa-square text-warning"></i> Negosiasi
					</span>

					<span>
						<i class="fa fa-square text-success"></i> Deal
					</span>
				</div>
			</div>
		</div>
		<div class="card-footer">
			<div class="row">
				<div class="col-sm-3 col-6">
					<div class="description-block border-right">
						<h5 class="description-header">IDR {{number_format($pendapatanChart/1000, 0, ',', '.')}}K</h5>
						<span class="description-text">TOTAL REVENUE</span>
					</div>
					<!-- /.description-block -->
				</div>
				<!-- /.col -->
				<div class="col-sm-3 col-6">
					<div class="description-block border-right">
						<h5 class="description-header">IDR {{number_format($pendapatanChartPending/1000, 0, ',', '.')}}K</h5>
						<span class="description-text">TOTAL PENDING</span>
					</div>
					<!-- /.description-block -->
				</div>
				<!-- /.col -->
				<div class="col-sm-3 col-6">
					<div class="description-block border-right">
						<h5 class="description-header">IDR {{number_format($pendapatanChartNegosiasi/1000, 0, ',', '.')}}K</h5>
						<span class="description-text">TOTAL NEGOSIASI</span>
					</div>
					<!-- /.description-block -->
				</div>
				<!-- /.col -->
				<div class="col-sm-3 col-6">
					<div class="description-block">
						<h5 class="description-header">IDR {{number_format($pendapatanChartDeal/1000, 0, ',', '.')}}K</h5>
						<span class="description-text">TOTAL DEAL</span>
					</div>
					<!-- /.description-block -->
				</div>
			</div>
			<!-- /.row -->
		</div>
	</div>
	<!-- /.card -->
</div>
<div class="col-lg-4">
	<div class="card">
		<div class="card-header">
			<h3 class="card-title">Popular Member</h3>

			<div class="card-tools">
				<button type="button" class="btn btn-tool" data-widget="collapse">
					<i class="fa fa-minus"></i>
				</button>
			</div>
		</div>
		<!-- /.card-header -->
		<div class="card-body p-0">
			<ul class="products-list product-list-in-card pl-2 pr-2">
				@foreach ($popularMember as $value)
				<li class="item">
					<div class="product-img">
						<img src="{{ (Storage::exists($value->profile_picture))? Storage::url($value->profile_picture) : asset('dist/img/avatar5.png') }}"
						alt="Product Image" class="img-size-50">
					</div>
					<div class="product-info">
						<a href="javascript:void(0)" class="product-title">{{$value->name}}
							<span class="badge badge-success float-right">IDR {{number_format($value->pendapatan/1000, 0, ',', '.')}}K</span></a>
							<span class="product-description">
								{{$value->noTelp}}
							</span>
						</div>
					</li>
					@endforeach

				</ul>
			</div>
			<!-- /.card-body -->
			<div class="card-footer text-center">
				<a href="{{ route('admin.member.index') }}" class="uppercase">View All Members</a>
			</div>
			<!-- /.card-footer -->
		</div>
	</div>
	@endsection

	@section('script')
	<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
	<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
	<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
	<script>
		$(document).ready(function() {
			$('.datatables').dataTable();
			$('.message-session').delay(3000).slideUp(600);
		});
		$(function () {
			'use strict'

			var ticksStyle = {
				fontColor: '#495057',
				fontStyle: 'bold'
			}

			var mode      = 'index'
			var intersect = true

			var $penghasilanChart = $('#penghasilan-chart')
			var penghasilanChart  = new Chart($penghasilanChart, {
				type   : 'bar',
				data   : {
					labels  : {!! json_encode($xAxis) !!},
					datasets: [
					{
						backgroundColor: '#c8c8cc',
						borderColor    : '#c8c8cc',
						data           : @json($chartPending)
					},
					{
						backgroundColor: '#ffc107',
						borderColor    : '#ffc107',
						data           : @json($chartNegosiasi)
					},
					{
						backgroundColor: '#28a745',
						borderColor    : '#28a745',
						data           :  @json($chartDeal)

					}
					]
				},
				options: {
					maintainAspectRatio: false,
					tooltips           : {
						mode     : mode,
						intersect: intersect
					},
					hover              : {
						mode     : mode,
						intersect: intersect
					},
					legend             : {
						display: false
					},
					scales             : {
						yAxes: [{
							// display: false,
							gridLines: {
								display      : true,
								lineWidth    : '4px',
								color        : 'rgba(0, 0, 0, .2)',
								zeroLineColor: 'transparent'
							},
							ticks    : $.extend({
								beginAtZero: true,

								// Include a dollar sign in the ticks
								callback: function (value, index, values) {
									if (value >= 1000000) {
										value /= 1000000
										value += 'JT'
									}
									return value
								}
							}, ticksStyle)
						}],
						xAxes: [{
							display  : true,
							gridLines: {
								display: false
							},
							ticks    : ticksStyle
						}]
					}
				}
			})
		});
	</script>
	@endsection

resources/views/admin/mitra.blade.php
@extends('temp.main')

@section('title-page', 'E-Bina | Admin - Mitra')

@section('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
<style media="screen">
  ul, li {
    list-style-type: none;
    margin-bottom: 20px;
  }
  .modal li p:first-child {
    margin-bottom: 10px;
    color: #626262;
    font-weight: normal;
  }
  .modal li p:last-child {
    font-weight: bold;
    color: #414141;
  }
  select, option {
    -webkit-appearance: none;
  }
</style>
@endsection

@section ('title-body', 'Mitra')

@section('content')
@if (Session::has('success_message') || Session::has('failed_message'))
<div class="col-12 message-session">
	<div class="alert alert-{{(Session::has('success_message'))? 'success' : 'danger'}} text-center">
    {{(Session::has('success_message'))? Session::get('success_message') : Session::get('failed_message')}}
  </div>
</div>
@endif
<div class="col-12">
	<div class="card">
		<div class="card-body">
			<div class="card-title text-center">List Mitra</div>
			<div class="table-responsive">
				<table class="table table-bordered table-hover datatables">
					<thead>
						<tr>
							<th>Nama</th>
							<th>Email</th>
							<th>Status</th>
							<th>Hp</th>
              <th>Detail</th>
							<th class="text-left">Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($mitra as $value)
						<tr>
							<td class="text-capitalize">{{ $value->nama }}</td>
							<td>{{ $value->email }}</td>
							<td>
                @if ($value->status == 'bergabung')
                  <small class="badge badge-success text-uppercase">{{ $value->status }}</small>
                @else
                  <small class="badge badge-secondary text-uppercase">{{ $value->status }}</small>
                @endif
              </td>
							<td>{{ $value->hp }}</td>
              <td>
                <button type="button" class="btn btn-link text-info" data-toggle="modal" data-target="#mitraLihat{{ $value->id }}">
                  Lihat Detail
                </button>
                <div class="modal fade" id="mitraLihat{{ $value->id }}" tabindex="-1" role="dialog" aria-labelledby="mitraLihat{{ $value->id }}Label"
                aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="h3">Detail Mitra {{ $value->nama }}</h1>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <ul>
                          <li>
                            <p class="mb-0">Nama Mitra</p>
                            <p class="text-capitalize">{{ $value->nama }}</p>
                          </li>
                          <li>
                            <p class="mb-0">Email Mitra</p>
                            <p>{{ $value->email }}</p>
                          </li>
                          <li>
                            <p class="mb-0">Status Saat Ini</p>
                            <p>{{ $value->status }}</p>
                          </li>
                          <li>
                            <p class="mb-0">Nomor Mitra</p>
                            <p>{{ $value->hp }}</p>
                          </li>
                          <li>
                            <p class="mb-0">Alamat Mitra</p>
                            <p>{{ $value->alamat }}</p>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
							<td>
                <button type="button" class="btn btn-link text-warning" data-toggle="modal" data-target="#mitra{{ $value->id }}">
                  Ubah Status
                </button>
                <div class="modal fade" id="mitra{{ $value->id }}" tabindex="-1" role="dialog" aria-labelledby="mitra{{ $value->id }}Label" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="h3">Ubah Status Saat Ini</h1>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <form action="{{ route('admin.mitra.update', $value->id) }}" method="post">
                          @csrf @method('PUT')
                          <div class="form-group">
                            <input type="text" class="form-control-plaintext text-capitalize" value="{{ $value->nama }}" readonly>
                          </div>
                          <select name="status" class="custom-select">
                            <option disabled>Status Saat Ini</option>
                            <option value="pending" @if ($value->status == 'pending') selected @endif>Pending</option>
                            <option value="bergabung"  @if ($value->status == 'bergabung') selected @endif>Bergabung</option>
                          </select>
                          <button type="submit" class="btn btn-success mt-3 float-right">Ubah Status</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                <form action="{{ route('admin.mitra.destroy', $value->id) }}" class="d-inline-block" onsubmit="return confirm('are you sure?')" method="POST">
									@csrf	@method('DELETE')
									<button class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Delete Klien">Hapus Mitra</button>
								</form>
              </td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
	$(document).ready(function() {
		$('.datatables').dataTable();
		$('.message-session').delay(3000).slideUp(600);
	});
</script>
@endsection