routes/web.php
<?php

Route::permanentRedirect('home', '/');
Route::view('support/thank-you', 'member.thanks')->name('support.thanks');
Route::view('/adminss', 'admin')->name('adminpage');
Route::view('mailable', 'admin.bantuan.template_mail');

Route::prefix('admin')->namespace('Auth')->name('admin.')->group(function () {
  Route::get('login','LoginController@showLoginForm')->name('login');
  Route::post('login', 'LoginController@login')->name('login');
  Route::get('register','RegisterController@showRegistrationForm')->name('register');
  Route::post('register', 'RegisterController@register')->name('register');
  Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::prefix('member')->namespace('Auth')->name('member.')->group(function () {
  Route::get('login','MemberLoginController@showLoginForm')->name('login');
  Route::post('login', 'MemberLoginController@login')->name('login');
  Route::get('register','MemberLoginController@showRegisterPage')->name('register');
  Route::post('register', 'MemberLoginController@register')->name('register');
  Route::post('logout', 'MemberLoginController@logout')->name('logout');
});

Route::namespace('Home')->name('home.')->group(function () {
  Route::get('/', 'HomeController@landing');
  Route::get('about', 'HomeController@about')->name('about');
  Route::get('mitra', 'HomeController@mitra')->name('mitra');
  Route::post('mitra', 'HomeController@storeMitra')->name('mitra.store');
  Route::get('support', 'HomeController@support')->name('support');
  Route::post('support', 'HomeController@supportStore')->name('support.store');
  Route::get('promo', 'HomeController@promosi')->name('promosi');
  Route::get('promo/{slug}', 'HomeController@showPromo')->name('promo.show');
  Route::get('syarat-dan-ketentuan', 'HomeController@peraturan')->name('peraturan');
  Route::get('profil', 'HomeController@profil')->name('profil');
  Route::get('profil/asd', 'HomeController@profil')->name('profil');
  Route::post('klien/create', 'HomeController@klienStore')->name('klien.store');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('auth')->group(function () {
  Route::resource('dashboard', 'DashboardController');
  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::put('member/activating/{id}', 'MemberController@activating')->name('member.activating');
  Route::resource('member', 'MemberController');
  Route::get('klien/edit-api/{id?}', 'KlienController@editApi')->name('klien.editAjax');
  Route::post('klien/update-api/{id?}', 'KlienController@updateApi')->name('klien.updateAjax');
  Route::resource('klien', 'KlienController');
  Route::get('penghasilan/fee', 'PenghasilanController@fee')->name('penghasilan.fee');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('landing-page', 'LandingPageController');
  Route::resource('promosi', 'PromosiController');
  Route::get('promosi/{slug}', 'PromosiController@show')->name('promosi.show');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
  Route::resource('partner', 'PartnerController');
  Route::resource('fitur', 'FiturController');
  Route::resource('mitra', 'MitraController');
});

Route::prefix('member')->namespace('Member')->name('member.')->middleware(['auth:member'])->group(function () {
  Route::resource('dashboard', 'DashboardController');

  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::resource('klien', 'KlienController');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('promosi', 'PromosiController');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
});

Route::namespace('Home')->name('home.')->group(function () {
Route::get('/{promo}/{member}', 'HomeController@getPromo')->name('getpromo')
->where([
  'promo' => '^(?!admin$).*$',
  'promo' => '^(?!member$).*$',
  'promo' => '^(?!profil$).*$',
  'promo' => '^(?!klien$).*$',
  'promo' => '^(?!support$).*$'
  ]);
});

app/Models/Penghasilan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Penghasilan extends Model
{
    protected $table = 'penghasilans';
    protected $fillable = ['idHarga', 'point', 'fee'];
    
    public function harga()
    {
        return $this->belongsTo('App\Models\Harga', 'idHarga', 'id')->withDefault([
            'harga' => 0,
            'tingkat' => 'Tidak ada!'
        ]);
    }
}

app/Http/Controllers/Admin/PenghasilanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Harga;
use App\Models\Klien;
use App\Models\Penghasilan;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DateTime;
use DB;

class PenghasilanController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(Request $request)
    {
        $data['popularMember'] = Klien::select(DB::raw('members.id, members.profile_picture, members.name, members.noTelp, sum(penghasilans.fee) as pendapatan'))
        ->where("kliens.status", 'deal')
        ->leftJoin('penghasilans', 'kliens.idHarga', '=', 'penghasilans.idHarga')
        ->leftJoin('members', 'kliens.idMember', '=', 'members.id')
        ->where('kliens.idMember', '<>', null)
        ->groupBy('members.id', 'members.profile_picture', 'members.name', 'members.noTelp')
        ->orderBy('pendapatan', 'desc')
        ->take(5)
        ->get();
        $data['pendapatan'] = Klien::where("kliens.status", 'deal')
        ->leftJoin('penghasilans', 'kliens.idHarga', '=', 'penghasilans.idHarga')
        ->sum("penghasilans.fee");
        $data['potensi_pendapatan'] = Klien::where("kliens.status", 'pending')
        ->orWhere("kliens.status", 'negosiasi')
        ->leftJoin('penghasilans', 'kliens.idHarga', '=', 'penghasilans.idHarga')
        ->sum("penghasilans.fee");
        $data['totalPendapatan'] = $data['pendapatan'] + $data['potensi_pendapatan'];
        $data['percentage'] = [
            'pendapatan' => ($data['totalPendapatan'] > 0)?($data['pendapatan']/$data['totalPendapatan']*100): 0,
            'potensi_pendapatan' => ($data['totalPendapatan'] > 0)?($data['potensi_pendapatan']/$data['totalPendapatan']*100) : 0
        ];
        $data['chartPending'] = [];
        $data['chartNegosiasi'] = [];
        $data['chartDeal'] = [];
        $data['xAxis'] = [];
        $data['pendapatanChart'] = 0;
        $data['pendapatanChartPending'] = 0;
        $data['pendapatanChartNegosiasi'] = 0;
        $data['pendapatanChartDeal'] = 0;
        $intRow = 0;

        $getDiffDay = 6;
        if (!empty($request->daterange)) {
            $getDaterange = explode(" - ", $request->daterange);
            $getStartDate = DateTime::createFromFormat("m/d/Y", $getDaterange[0]);
            $getEndDate = DateTime::createFromFormat("m/d/Y", $getDaterange[1]);
            $interval = date_diff($getStartDate, $getEndDate);
            $getDiffDay = $interval->days;
            $data['startDate'] = $getStartDate->format("m/d/Y");
            $data['endDate'] = $getEndDate->format("m/d/Y");
        }
        else {
            $data['startDate'] = Date('m/d/Y', strtotime('-6 days'));
            $data['endDate'] = Date('m/d/Y');
        }
        for ($i=0; $i <= $getDiffDay; $i++) {
            $data['xAxis'][($intRow)] =  date("M d", strtotime("+".$i." day", strtotime($data['startDate'])));
            $data['chartPending'][($intRow)] = Klien::where('kliens.status', 'pending')
            ->whereDate('kliens.created_at', Date('Y-m-d', strtotime("+".$i." day", strtotime($data['startDate']))))
            ->leftJoin('penghasilans', 'kliens.idHarga', '=', 'penghasilans.idHarga')
            ->sum('penghasilans.fee');
            $data['pendapatanChartPending'] += $data['chartPending'][($intRow)];
            $data['chartNegosiasi'][($intRow)] = Klien::where('kliens.status', 'negosiasi')
            ->whereDate('kliens.created_at', Date('Y-m-d', strtotime("+".$i." day", strtotime($data['startDate']))))
            ->leftJoin('penghasilans', 'kliens.idHarga', '=', 'penghasilans.idHarga')
            ->sum('penghasilans.fee');
            $data['pendapatanChartNegosiasi'] += $data['chartNegosiasi'][($intRow)];
            $data['chartDeal'][($intRow)] = Klien::where('kliens.status', 'deal')
            ->whereDate('kliens.created_at', Date('Y-m-d', strtotime("+".$i." day", strtotime($data['startDate']))))
            ->leftJoin('penghasilans', 'kliens.idHarga', '=', 'penghasilans.idHarga')
            ->sum('penghasilans.fee');
            $data['pendapatanChartDeal'] += $data['chartDeal'][($intRow)];
            $data['pendapatanChart'] += $data['chartPending'][($intRow)] + $data['chartNegosiasi'][($intRow)] + $data['chartDeal'][($intRow)];
            $intRow += 1;
        }
        return view('admin.penghasilan.penghasilan_chart')->with($data);
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function fee()
    {
        $data['penghasilan'] = Penghasilan::all();
        return view('admin.penghasilan.penghasilan_index')->with($data);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $data['harga'] = Harga::all();
        return view('admin.penghasilan.penghasilan_create')->with($data);
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $request->validate([
            'idHarga' => 'required|int|unique:penghasilans',
            'point' => 'required|int',
            'fee' => 'required|int'
            ]);

            Penghasilan::create([
                'idHarga' => $request->idHarga,
                'point' => $request->point,
                'fee' => $request->fee
                ]);
                $request->session()->flash('success_message', 'Success Adding Konfigurasi Penghasilan');
                return redirect()->route('admin.penghasilan.index');
            }

            /**
            * Display the specified resource.
            *
            * @param  int  $id
            * @return \Illuminate\Http\Response
            */
            public function show($id)
            {
                //
            }

            /**
            * Show the form for editing the specified resource.
            *
            * @param  int  $id
            * @return \Illuminate\Http\Response
            */
            public function edit($id)
            {
                $data['harga'] = Harga::all();
                $data['penghasilan'] = Penghasilan::findOrfail($id);
                return view('admin.penghasilan.penghasilan_edit')->with($data);
            }

            /**
            * Update the specified resource in storage.
            *
            * @param  \Illuminate\Http\Request  $request
            * @param  int  $id
            * @return \Illuminate\Http\Response
            */
            public function update(Request $request, $id)
            {
                $request->validate([
                    'idHarga' => 'required|int|unique:penghasilans,idHarga,' . $id,
                    'point' => 'required|int',
                    'fee' => 'required|int'
                    ]);

                    Penghasilan::where('id', $id)->update([
                        'idHarga' => $request->idHarga,
                        'point' => $request->point,
                        'fee' => $request->fee
                        ]);
                        $request->session()->flash('success_message', 'Success Updating Konfigurasi Penghasilan');
                        return redirect()->route('admin.penghasilan.index');
                    }

                    /**
                    * Remove the specified resource from storage.
                    *
                    * @param  int  $id
                    * @return \Illuminate\Http\Response
                    */
                    public function destroy(Request $request, $id)
                    {
                        Penghasilan::where('id', $id)->delete();
                        $request->session()->flash('success_message', 'Success Deleting Konfigurasi Penghasilan');
                        return redirect()->route('admin.penghasilan.index');
                    }
                }

resources/views/admin/penghasilan/penghasilan_chart.blade.php
@extends('temp.main')

@section('title-page', 'E-Bina | Admin - Penghasilan')

@section('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
@endsection

@section ('title-body', 'Penghasilan')

@section('content')
@if (Session::has('success_message') || Session::has('failed_message'))
<div class="col-12 message-session">
    <div class="alert alert-{{(Session::has('success_message'))? 'success' : 'danger'}} text-center">{{(Session::has('success_message'))? Session::get('success_message') : Session::get('failed_message')}}</div>
</div>
@endif
<div class="col-md-4 col-sm-6 col-12">
    <div class="info-box bg-primary-gradient">
        <span class="info-box-icon"><i class="fa fa-money-bill-wave-alt"></i></span>
        
        <div class="info-box-content">
            <span class="info-box-text">Total Pendapatan</span>
            <span class="info-box-number">Rp {{number_format($pendapatan+$potensi_pendapatan, 0, ',', '.')}}</span>
            
            <div class="progress">
                <div class="progress-bar" style="width: 100%"></div>
            </div>
            <span class="progress-description">
                100% from (pendapatan + potensi)
            </span>
        </div>
        <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
</div>
<div class="col-md-4 col-sm-6 col-12">
    <div class="info-box bg-success-gradient">
        <span class="info-box-icon"><i class="fa fa-money-bill-wave-alt"></i></span>
        
        <div class="info-box-content">
            <span class="info-box-text">Pendapatan</span>
            <span class="info-box-number">Rp {{number_format($pendapatan, 0, ',', '.')}}</span>
            
            <div class="progress">
                <div class="progress-bar" style="width: {{$percentage['pendapatan']}}%"></div>
            </div>
            <span class="progress-description">
                {{(is_float($percentage['pendapatan']))? number_format((float)$percentage['pendapatan'], 1) : $percentage['pendapatan']}}% from total
            </span>
        </div>
        <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
</div>
<div class="col-md-4 col-sm-6 col-12">
    <div class="info-box bg-warning-gradient">
        <span class="info-box-icon"><i class="fa fa-money-bill-wave-alt"></i></span>
        
        <div class="info-box-content">
            <span class="info-box-text">Potensi Pendapatan</span>
            <span class="info-box-number">Rp {{number_format($potensi_pendapatan, 0, ',', '.')}}</span>
            
            <div class="progress">
                <div class="progress-bar" style="width: {{$percentage['potensi_pendapatan']}}%"></div>
            </div>
            <span class="progress-description">
                {{(is_float($percentage['potensi_pendapatan']))? number_format((float)$percentage['potensi_pendapatan'], 1) : $percentage['potensi_pendapatan']}}% from total
            </span>
        </div>
        <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
</div>
<div class="col-lg-8">
    
    <div class="card">
        <div class="card-header no-border">
            <div class="d-flex justify-content-between">
                <h3 class="card-title">Penghasilan</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
                {{-- <a href="javascript:void(0);">View Report</a> --}}
            </div>
        </div>
        <div class="card-body" style="overflow-x: auto;">
            <form action="{{ route('admin.penghasilan.index') }}" method="GET">
                <div class="row col-12 px-0">
                    <div class="col-md-4 col-12">
                        <input type="text" name="daterange" class="form-control input-daterange">
                    </div>
                    <div class="col-md-6 col-12">
                        <button type="submit" class="btn btn-primary btn-md float-left">Filter</button>
                    </div>
                </div>
            </form>
            <div class="col-12" style="min-width: 500px;">
                <div class="d-flex">
                    <p class="d-flex flex-column">
                        <span>Revenue Over Time</span>
                    </p>
                    <p class="ml-auto d-flex flex-column text-right">
                        <span class="text-muted">Date: {{$startDate}} - {{$endDate}}</span>
                    </p>
                </div>
                <!-- /.d-flex -->
                
                <div class="position-relative mb-4">
                    <canvas id="penghasilan-chart" height="200"></canvas>
                </div>
                
                <div class="d-flex flex-row justify-content-end">
                    <span class="mr-2">
                        <i class="fa fa-square text-gray"></i> Pending
                    </span>
                    
                    <span>
                        <i class="fa fa-square text-warning"></i> Negosiasi
                    </span>
                    
                    <span>
                        <i class="fa fa-square text-success"></i> Deal
                    </span>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-sm-3 col-6">
                    <div class="description-block border-right">
                        <h5 class="description-header">IDR {{number_format($pendapatanChart/1000, 0, ',', '.')}}K</h5>
                        <span class="description-text">TOTAL REVENUE</span>
                    </div>
                    <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                    <div class="description-block border-right">
                        <h5 class="description-header">IDR {{number_format($pendapatanChartPending/1000, 0, ',', '.')}}K</h5>
                        <span class="description-text">TOTAL PENDING</span>
                    </div>
                    <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                    <div class="description-block border-right">
                        <h5 class="description-header">IDR {{number_format($pendapatanChartNegosiasi/1000, 0, ',', '.')}}K</h5>
                        <span class="description-text">TOTAL NEGOSIASI</span>
                    </div>
                    <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                    <div class="description-block">
                        <h5 class="description-header">IDR {{number_format($pendapatanChartDeal/1000, 0, ',', '.')}}K</h5>
                        <span class="description-text">TOTAL DEAL</span>
                    </div>
                    <!-- /.description-block -->
                </div>
            </div>
            <!-- /.row -->
        </div>
    </div>
    <!-- /.card -->
</div>
<div class="col-lg-4">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Popular Member</h3>
            
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <ul class="products-list product-list-in-card pl-2 pr-2">
                @foreach ($popularMember as $value)
                <li class="item">
                    <div class="product-img">
                        <img src="{{ (Storage::exists($value->profile_picture))? Storage::url($value->profile_picture) : asset('dist/img/avatar5.png') }}" alt="Product Image" class="img-size-50">
                    </div>
                    <div class="product-info">
                        <a href="javascript:void(0)" class="product-title">{{$value->name}}
                            <span class="badge badge-success float-right">IDR {{number_format($value->pendapatan/1000, 0, ',', '.')}}K</span></a>
                            <span class="product-description">
                                {{$value->noTelp}}
                            </span>
                        </div>
                    </li>
                    @endforeach
                    
                </ul>
            </div>
            <!-- /.card-body -->
            <div class="card-footer text-center">
                <a href="{{ route('admin.member.index') }}" class="uppercase">View All Members</a>
            </div>
            <!-- /.card-footer -->
        </div>
    </div>
    @endsection
    
    @section('script')
    <script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
    <script src="{{ asset('plugins/daterangepicker/moment.min.js') }}"></script>
    <script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.message-session').delay(3000).slideUp(600);
            $('.input-daterange').daterangepicker({
                "maxSpan": {
                    "days": 30
                },
                "startDate": "{{$startDate}}",
                "endDate": "{{$endDate}}"
            });
        });
        $(function () {
            'use strict'
            
            var ticksStyle = {
                fontColor: '#495057',
                fontStyle: 'bold'
            }
            
            var mode      = 'index'
            var intersect = true
            
            var $penghasilanChart = $('#penghasilan-chart')
            var penghasilanChart  = new Chart($penghasilanChart, {
                type   : 'bar',
                data   : {
                    labels  : {!! json_encode($xAxis) !!},
                    datasets: [
                    {
                        backgroundColor: '#c8c8cc',
                        borderColor    : '#c8c8cc',
                        data           : {!! json_encode($chartPending) !!}
                    },
                    {
                        backgroundColor: '#ffc107',
                        borderColor    : '#ffc107',
                        data           : {!! json_encode($chartNegosiasi) !!}
                    },
                    {
                        backgroundColor: '#28a745',
                        borderColor    : '#28a745',
                        data           : {!! json_encode($chartDeal) !!}
                    }
                    ]
                },
                options: {
                    maintainAspectRatio: false,
                    tooltips           : {
                        mode     : mode,
                        intersect: intersect
                    },
                    hover              : {
                        mode     : mode,
                        intersect: intersect
                    },
                    legend             : {
                        display: false
                    },
                    scales             : {
                        yAxes: [{
                            // display: false,
                            gridLines: {
                                display      : true,
                                lineWidth    : '4px',
                                color        : 'rgba(0, 0, 0, .2)',
                                zeroLineColor: 'transparent'
                            },
                            ticks    : $.extend({
                                beginAtZero: true,
                                
                                // Include a dollar sign in the ticks
                                callback: function (value, index, values) {
                                    if (value >= 1000000) {
                                        value /= 1000000
                                        value += 'JT'
                                    }
                                    return value
                                }
                            }, ticksStyle)
                        }],
                        xAxes: [{
                            display  : true,
                            gridLines: {
                                display: false
                            },
                            ticks    : ticksStyle
                        }]
                    }
                }
            })
        });
    </script>
    @endsection
    

resources/views/admin/penghasilan/penghasilan_index.blade.php
@extends('temp.main')

@section('title-page', 'E-Bina | Admin - Pengaturan Fee')

@section('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section ('title-body', 'Pengaturan Fee')

@section('content')
	@if (Session::has('success_message') || Session::has('failed_message'))
		<div class="col-12 message-session">
			<div class="alert alert-{{(Session::has('success_message'))? 'success' : 'danger'}} text-center">
				{{ (Session::has('success_message'))? Session::get('success_message') : Session::get('failed_message') }}
			</div>
		</div>
	@endif
	@foreach ($penghasilan as $value)
		<div class="col-12">
			<div class="invoice p-3 mb-3">
				<div class="row invoice-info">
					<div class="col-sm-4 invoice-col">
						<p class="mb-0 text-capitalize"><span class="font-weight-bold">Tingkat: </span> {{ $value->harga->tingkat }}</p>
						<p class="mb-0 text-capitalize"><span class="font-weight-bold">Harga: </span>  {{ $value->harga->harga }}rb/bulan</p>
					</div>
					<div class="col-sm-4 invoice-col">
						<p class="mb-0 text-capitalize"><span class="font-weight-bold">Point:</span> {{ $value->point . 'pt'}}</p>
						<p class="mb-0 text-capitalize"><span class="font-weight-bold">Fee / Pendapatan:</span> {{ number_format($value->fee, 0, ',', '.') }}</p>
					</div>
					<div class="col-sm-4">
						<form action="{{ route('admin.penghasilan.destroy', ['id'=> $value->id]) }}" method="post">
							@csrf	@method('DELETE')
							<button type="submit" class="btn btn-sm btn-danger float-right"><i class="fa fa-trash"></i></button>
						</form>
							<a href="{{ route('admin.penghasilan.edit', ['id'=> $value->id]) }}" class="btn btn-sm btn-warning float-right mr-3">
								<i class="fa fa-edit"></i>
							</a>
					</div>
				</div>
			</div>
		</div>
	@endforeach
	@if (count($penghasilan) < 3)
		<div class="col-12">
			<a href="{{ route('admin.penghasilan.create') }}" class="btn btn-primary float-right">Tambah Konfigurasi</a>
		</div>
	@endif
@endsection

@section('script')
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
	$(document).ready(function() {
		$('.message-session').delay(3000).slideUp(600);
	});
</script>
@endsection