routes/web.php
<?php

Route::permanentRedirect('home', '/');
Route::view('support/thank-you', 'member.thanks')->name('support.thanks');
Route::view('/adminss', 'admin')->name('adminpage');
Route::view('mailable', 'admin.bantuan.template_mail');

Route::prefix('admin')->namespace('Auth')->name('admin.')->group(function () {
  Route::get('login','LoginController@showLoginForm')->name('login');
  Route::post('login', 'LoginController@login')->name('login');
  Route::get('register','RegisterController@showRegistrationForm')->name('register');
  Route::post('register', 'RegisterController@register')->name('register');
  Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::prefix('member')->namespace('Auth')->name('member.')->group(function () {
  Route::get('login','MemberLoginController@showLoginForm')->name('login');
  Route::post('login', 'MemberLoginController@login')->name('login');
  Route::get('register','MemberLoginController@showRegisterPage')->name('register');
  Route::post('register', 'MemberLoginController@register')->name('register');
  Route::post('logout', 'MemberLoginController@logout')->name('logout');
});

Route::namespace('Home')->name('home.')->group(function () {
  Route::get('/', 'HomeController@landing');
  Route::get('about', 'HomeController@about')->name('about');
  Route::get('mitra', 'HomeController@mitra')->name('mitra');
  Route::post('mitra', 'HomeController@storeMitra')->name('mitra.store');
  Route::get('support', 'HomeController@support')->name('support');
  Route::post('support', 'HomeController@supportStore')->name('support.store');
  Route::get('promo', 'HomeController@promosi')->name('promosi');
  Route::get('promo/{slug}', 'HomeController@showPromo')->name('promo.show');
  Route::get('syarat-dan-ketentuan', 'HomeController@peraturan')->name('peraturan');
  Route::get('profil', 'HomeController@profil')->name('profil');
  Route::get('profil/asd', 'HomeController@profil')->name('profil');
  Route::post('klien/create', 'HomeController@klienStore')->name('klien.store');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('auth')->group(function () {
  Route::resource('dashboard', 'DashboardController');
  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::put('member/activating/{id}', 'MemberController@activating')->name('member.activating');
  Route::resource('member', 'MemberController');
  Route::get('klien/edit-api/{id?}', 'KlienController@editApi')->name('klien.editAjax');
  Route::post('klien/update-api/{id?}', 'KlienController@updateApi')->name('klien.updateAjax');
  Route::resource('klien', 'KlienController');
  Route::get('penghasilan/fee', 'PenghasilanController@fee')->name('penghasilan.fee');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('landing-page', 'LandingPageController');
  Route::resource('promosi', 'PromosiController');
  Route::get('promosi/{slug}', 'PromosiController@show')->name('promosi.show');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
  Route::resource('partner', 'PartnerController');
  Route::resource('fitur', 'FiturController');
  Route::resource('mitra', 'MitraController');
});

Route::prefix('member')->namespace('Member')->name('member.')->middleware(['auth:member'])->group(function () {
  Route::resource('dashboard', 'DashboardController');

  Route::put('profil/change-password', 'ProfilController@changePassword')->name('profil.change.password');
  Route::put('profil/picture-update', 'ProfilController@UpdateProfile')->name('profil.picture_update');
  Route::resource('profil', 'ProfilController');
  Route::resource('klien', 'KlienController');
  Route::resource('penghasilan', 'PenghasilanController');
  Route::resource('promosi', 'PromosiController');
  Route::resource('aturan', 'AturanController');
  Route::resource('bantuan', 'BantuanController');
});

Route::namespace('Home')->name('home.')->group(function () {
Route::get('/{promo}/{member}', 'HomeController@getPromo')->name('getpromo')
->where([
  'promo' => '^(?!admin$).*$',
  'promo' => '^(?!member$).*$',
  'promo' => '^(?!profil$).*$',
  'promo' => '^(?!klien$).*$',
  'promo' => '^(?!support$).*$'
  ]);
});

app/Http/Controllers/Admin/AturanController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Peraturan;

class AturanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peraturan = Peraturan::all();
        return view('admin.aturan.aturan_index', ['peraturan' => $peraturan]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.aturan.aturan_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $tambah_aturan = new Peraturan;

      $tambah_aturan->judul = $request->judul;
      $tambah_aturan->deskripsi = $request->deskripsi;

      $tambah_aturan->save();
      return redirect()->route('admin.aturan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editAturan = Peraturan::findOrFail($id);
        return view('admin.aturan.aturan_edit', ['editAturan' => $editAturan]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $updatePeraturan = Peraturan::findOrFail($id);

      $updatePeraturan->judul = $request->judul;
      $updatePeraturan->deskripsi = $request->deskripsi;

      $updatePeraturan->save();
      return redirect()->route('admin.aturan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $hapusPeraturan = Peraturan::findOrFail($id);
      $hapusPeraturan->delete();
      return redirect()->back();
    }
}

app/Http/Controllers/Member/AturanController.php
<?php

namespace App\Http\Controllers\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Peraturan;

class AturanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peraturan = Peraturan::all();
        return view('member.aturan.aturan_index', ['peraturan' => $peraturan]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/aturan/aturan_create.blade.php
@extends('temp.main')
@section('title-page', 'Tambah Aturan')
@section('css')
  <link rel="stylesheet" href="{{ asset('plugins/trumbowyg/dist/ui/trumbowyg.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.css') }}">
  <style media="screen">
    .trumbowyg-box .trumbowyg-editor {
      background-color: #fff;
    }
  </style>
@endsection
@section('title-body', 'Tambah Aturan')
@section('content')
<main class="col-12">
  <form action="{{ route('admin.aturan.store') }}" method="post">
    @csrf
    <input type="text" class="form-control mb-3" name="judul" placeholder="Judul Aturan" autocomplete="off">
    <textarea name="deskripsi" rows="10" placeholder="Deskripsi Aturan"></textarea>
    <button type="submit" class="btn btn-success float-right mt-3">Tambah Aturan</button>
  </form>
</main>
@endsection
@section('script')
  <script src="{{ asset('plugins/trumbowyg/dist/trumbowyg.min.js') }}" charset="utf-8"></script>
  <script src="{{ asset('plugins/trumbowyg/dist/plugins/cleanpaste/trumbowyg.cleanpaste.min.js') }}"></script>
  <script src="{{ asset('plugins/trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js') }}"></script>
  <script>
    $("textarea[name='deskripsi']").trumbowyg({
      semantic: true,
      removeformatPasted: false,
      minimalLinks: true
    });
    $("textarea[name='deskripsi']").trumbowyg({
      btns: [
        ['foreColor', 'backColor']
      ]
    });
  </script>
@endsection

resources/views/admin/aturan/aturan_edit.blade.php
@extends('temp.main')
@section('title-page', 'Edit Aturan')
@section('css')
  <link rel="stylesheet" href="{{ asset('plugins/trumbowyg/dist/ui/trumbowyg.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.css') }}">
  <style media="screen">
    .trumbowyg-box .trumbowyg-editor {
      background-color: #fff;
    }
  </style>
@endsection
@section('title-body', 'Edit Aturan')
@section('content')
<main class="col-12">
  <form action="{{ route('admin.aturan.update', $editAturan->id) }}" method="post">
    @csrf @method('PUT')
    <input type="text" name="judul" class="form-control mb-3" placeholder="Judul Peraturan" value="{{ $editAturan->judul }}">
    <textarea name="deskripsi" rows="10" placeholder="Deskripsi Peraturan">{{ $editAturan->deskripsi }}</textarea>
    <button type="submit" class="btn btn-success float-right mt-3">Update Peraturan</button>
  </form>
</main>
@endsection
@section('script')
  <script src="{{ asset('plugins/trumbowyg/dist/trumbowyg.min.js') }}" charset="utf-8"></script>
  <script src="{{ asset('plugins/trumbowyg/dist/plugins/cleanpaste/trumbowyg.cleanpaste.min.js') }}"></script>
  <script>
    $("textarea[name='deskripsi']").trumbowyg();
  </script>
@endsection

resources/views/admin/aturan/aturan_index.blade.php
@extends('temp.main')
@section('title-page', 'E-Bina | Admin - Aturan')
@section('css')
	<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
	<style>
		#menuPeraturan div {
			border-radius: 5px 0 0 5px;
			overflow: hidden;
			border-top: 1px solid #c8c8c8;
			border-left: 1px solid #c8c8c8;
		}
		#menuPeraturan div a {
			border-radius: 5px 0 0 5px !important;
			text-transform: capitalize;
		}
		#menuPeraturan div a:last-of-type {
			border-bottom: 1px solid #c8c8c8;
		}
		#menuPeraturan div a[aria-selected='true']{
			background-color: #e7ebf0 !important;
			color: #5C8EC7 !important;
		}
		#listPeraturan .tab-content {
			border: 1px solid #c8c8c8;
		}
		#listPeraturan h2 {
			display: flex;
			align-items: center;
		}
		#listPeraturan h2 small:first-of-type {
			margin-left: auto;
		}
		#listPeraturan h2 small {
			font-size: 16px;
		}
	</style>
@endsection
@section ('title-body', 'Aturan')
@section('content')
	@if (Session::has('success_message') || Session::has('failed_message'))
	<div class="col-12 message-session">
		<div class="alert alert-{{(Session::has('success_message'))? 'success' : 'danger'}} text-center">
			{{(Session::has('success_message'))? Session::get('success_message') : Session::get('failed_message')}}
		</div>
	</div>
	@endif
	<main class="col-12">
	  <div class="row">
			<div class="col-3 pr-0" id="menuPeraturan">
		    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
					@foreach ($peraturan as $each)
						<a class="nav-link" id="v-pills-peraturan{{ $each->id }}-tab" data-toggle="pill" href="#v-pills-peraturan{{ $each->id }}" role="tab"
						aria-controls="v-pills-peraturan{{ $each->id }}" aria-selected="false">{{ $each->judul }}</a>
					@endforeach
		    </div>
		  </div>
		  <div class="col-9 pl-0" id="listPeraturan">
		    <div class="tab-content px-4 py-3" id="v-pills-tabContent">
					@foreach ($peraturan as $each)
		      <div class="tab-pane fade" id="v-pills-peraturan{{ $each->id }}" role="tabpanel" aria-labelledby="v-pills-peraturan{{ $each->id }}-tab">
						<h2 class="text-capitalize">{{ $each->judul }}
							<small>
								<form action="{{ route('admin.aturan.destroy', $each->id) }}" method="post">
									@csrf @method('DELETE')
									<button type="submit" value="{{ $each->id }}" class="text-danger pl-0 py-0 btn btn-link">
										<i class="text-danger fas fa-trash-alt"></i>
									</button>
								</form>
							</small>
							<small><a href="{{ route('admin.aturan.edit', $each->id) }}"><i class="fas fa-edit"></i></a></small>
						</h2>
		      	{!! $each->deskripsi !!}
		      </div>
					@endforeach
		    </div>
				<a href="{{ route('admin.aturan.create') }}" class="btn btn-info mt-3 float-right">Tambah Aturan</a>
		  </div>
	  </div>
	</main>
@endsection
@section('script')
	<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
	<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
	<script>
		$(document).ready(function() {
			$('.message-session').delay(3000).slideUp(600);
			$("#menuPeraturan .nav-pills .nav-link:first-of-type").addClass("active").attr("aria-selected", "true")
			$(".tab-content .tab-pane.fade:first-of-type").addClass("show active");
		});
	</script>
@endsection